db_url: mongodb+srv://aryanpahari4_db_user:kPpfqc4zu7AQo2bx@cluster0.n0bsir6.mongodb.net/?appName=Cluster0
apiKey: AIzaSyA0Qh58j2f6o5EMxc5wX3y0obNu2mKZ6Jw
authDomain: indiancommunity-61fb9.firebaseapp.com
projectId: indiancommunity-61fb9
storageBucket: indiancommunity-61fb9.firebasestorage.app
messagingSenderId: 952444759681
appId: 1:952444759681:web:bb2972dfb1d4a81b62e780
measurementId: G-LN770MP1WD